server/django/conf/project_template/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

server/localeurl/urls.py
from django.conf.urls.defaults import *
from localeurl.views import change_locale

urlpatterns = patterns('',
	url(r'^change/', change_locale, name='localeurl_change_locale'),
)

server/urls.py
"""adds ebooks prefix to urls"""
from django.contrib import admin
from django.conf.urls.defaults import *

try:
    from settings import ROOT_URL
except ImportError:
    ROOT_URL = r''

from spec.logger import create_log

create_log()

admin.autodiscover()

urlpatterns = patterns('',
    (ROOT_URL, include('urls_root')),
)

server/book/forms.py
'''Defines forms for admin view'''
# -*- coding: utf-8 -*-

from book.models import Author, Book, Language, BookFile, Annotation

#from forms.views_forms import available_languages
from django import forms
from django.forms.widgets import RadioInput

from django.db.models.fields.related import ManyToManyRel

from book.widgets import AuthorWidget, LanguageWidget, AnnotationWidget


CREDIT_CHOICES = (
    ('0', 'DOUBTFUL'),
    ('1', 'CREDIBLE'),
    ('2', 'VERIFIED'),
)


class BookForm(forms.ModelForm):
    '''form for represent model.Book in admin change veiw'''
    class Meta:
        '''defines model for this form '''
        model = Book

    author = forms.CharField(widget=AuthorWidget(rel=ManyToManyRel(to=Author)), 
                                            label='Authors') #TODO help_text
    language = forms.ModelChoiceField(queryset=Language.objects.all(), 
                        widget=LanguageWidget(choices=Language.objects.exclude(book__isnull=True)[1:]))
    credit = forms.IntegerField(widget=forms.RadioSelect(choices=CREDIT_CHOICES))

    annotation = forms.CharField(widget=AnnotationWidget
                                (rel=ManyToManyRel(to=Annotation)))

    def save(self, commit=True):
        """
        Saves this form's data into model using save_book function
        Returns ''instance''.
        """
        if self.instance.pk is None:
            fail_message = 'created'
        else:
            fail_message = 'changed'
        return save_book(self, self.instance, self._meta.fields,
                             fail_message, commit, exclude=self._meta.exclude)


class AuthorForm(forms.ModelForm):
    '''form for represent model.Author in admin change veiw'''
    class Meta:
        '''defines model for this form '''
        model = Author

    credit = forms.IntegerField(widget=forms.Select(choices=CREDIT_CHOICES))

class BookFileForm(forms.ModelForm):
    '''form for represent model.Author in admin change veiw'''
    class Meta:
        '''defines model for this form '''
        model = BookFile

    credit = forms.IntegerField(widget=forms.Select(choices=CREDIT_CHOICES))
    link = forms.CharField(widget=forms.TextInput(attrs={'size':'50'}))
    type = forms.CharField(widget=forms.TextInput(attrs={'size':'50'}))
    img_link = forms.CharField(widget=forms.TextInput(attrs={'size':'50'}), 
                                                                required=False)



def save_book(form, instance, fields=None, fail_message='saved',
                  commit=True, exclude=None):
    """
    Saves book, exracts authors id for saving
    """
    from django.db import models
    opts = instance._meta
    if form.errors:
        raise ValueError("The %s could not be %s because the data didn't"
                         " validate." % (opts.object_name, fail_message))
    cleaned_data = form.cleaned_data

    ############### my logic for saving


    authors_list = eval(cleaned_data.pop('author'))
    authors = list()
    for i in authors_list:
        authors.append(int(i))
    cleaned_data['author'] = authors


    annotations_list = eval(cleaned_data.pop('annotation'))
    annotations = list()
    for i in annotations_list:
        annotations.append(int(i))

    cleaned_data['annotation'] = annotations

    ################

    file_field_list = []
    for field in opts.fields:
        if not field.editable or isinstance(field, models.AutoField) \
                or not field.name in cleaned_data:
            continue
        if fields and field.name not in fields:
            continue
        if exclude and field.name in exclude:
            continue
        # OneToOneField doesn't allow assignment of None. Guard against that
        # instead of allowing it and throwing an error.
        if isinstance(field, models.OneToOneField) and cleaned_data[field.name] is None:
            continue
        # Defer saving file-type fields until after the other fields, so a
        # callable upload_to can use the values from other fields.
        if isinstance(field, models.FileField):
            file_field_list.append(field)
        else:
            field.save_form_data(instance, cleaned_data[field.name])

    for field in file_field_list:
        field.save_form_data(instance, cleaned_data[field.name])

    # Wrap up the saving of m2m data as a function.
    def save_m2m():
        ''' defines how to save object's m2m fields'''
        opts = instance._meta
        cleaned_data = form.cleaned_data
        for field in opts.many_to_many:
            if fields and field.name not in fields:
                continue
            if field.name in cleaned_data:
                field.save_form_data(instance, cleaned_data[field.name])
    if commit:
        # If we are committing, save the instance and the m2m data immediately.
        instance.save()
        save_m2m()
    else:
        # We're not committing. Add a method to the form to allow deferred
        # saving of m2m data.
        form.save_m2m = save_m2m
    return instance

server/templates/epub/add_book.html
{% extends "epub/base.xhtml" %}
{% load i18n %}

{% block title %}{% trans "Add book." %}{% endblock %}

{% block content %}
    <br/>
    <div align="center">
    <table width="80%">
        <tr>
            <td align="center">
                {% trans "Create book from txt file" %}
            </td>
            <td align="center">
                {% trans "Create book from doc file" %}
            </td>
        </tr>
        <tr>
            <td align="center">
                <span id="txt">
                    <a href="create/txt/">
                        <img src="/{{ MEDIA_URL }}/pic/notepad.png" title="{% trans "Create book from txt file" %}" alt="{% trans "Create book from txt file" %}">
                    </a>
                </span>
            </td>
            <td align="center">
                <span id="doc">
                    <a href="create/doc/">
                        <img src="/{{ MEDIA_URL }}/pic/doc.jpg" title="{% trans "Create book from doc file" %}" alt="{% trans "Create book from doc file" %}">
                    </a>
                </span>
            </td>
        </tr>
    </table>
    </div>
{% endblock %}

server/templates/epub/add_doc_form.html
{% extends "epub/base.xhtml" %}
{% load i18n %}

{% block title %}
{% trans "Add doc book." %}
{% endblock %}

{% block content %}
    <p>{% trans "Please choose .doc file" %}</p>
    {% if messages %}
        {% for message in messages %}
            <div id='message'>
                {% trans "Message" %}: {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% if form.errors %}
        <p style="color: red;">
            {% blocktrans with form.errors|pluralize as errors %} 
                Please correct the error{{ errors }} below 
            {% endblocktrans %}
            {% trans sometest %}
        </p>
    {% endif %}
    {% if errors %}
        {% for error in errors %}
            <div id='error'>
                {{ error }}
            </div>
        {% endfor %}
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value='{% trans "Submit" %}'/>
    </form>
{% endblock %}

server/templates/epub/epub_form.html
{% extends "epub/base.xhtml" %}
{% load i18n %}

{% block title %}{% trans "Epub creation" %}{% endblock %}

{% block content %}
    {% if errors %}
        {% for error in errors %}
        <div id='error'>
            {% trans "Error" %}: {{ error }}
        </div>
        {% endfor %}
    {% endif %}

    {% if messages %}
        {% for message in messages %}
            <div id='message'>
                {% trans "Message" %}: {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">
        <table>
            {{ form.as_table }}
        </table>
        <div id="submit">
            <input type="submit" value="{% trans "Create" %}"/>
        </div>

    </form>
{% endblock %}

server/templates/epub/get_book_from_libru.html
{% extends "epub/base.xhtml" %}

{% block title %}Get book from libru{% endblock %}

{% block content %}
    {% if errors %}
        {% for error in errors %}
            <div id='error'>
                Error: {{ error }}
            </div>
        {% endfor %}
    {% endif %}

    {% if messages %}
        {% for message in messages %}
            <div id='message'>
                Message: {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <form action="" method="get" enctype="multipart/form-data">
        <div id="link">
            <table>
                <tr><th><label for="id_link">Lib.ru link:</label></th><td><input name="link" id="id_link" /></td></tr>
            </table>
        </div>
        <div id="submit">
            <input type="submit" value="Get book"/>
        </div>
    </form>
{% endblock %}