server/django/conf/project_template/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

server/localeurl/urls.py
from django.conf.urls.defaults import *
from localeurl.views import change_locale

urlpatterns = patterns('',
	url(r'^change/', change_locale, name='localeurl_change_locale'),
)

server/sentry/urls.py
import os
import re

from django.conf.urls.defaults import *

from sentry.conf import KEY
from sentry import views
from sentry.feeds import MessageFeed, SummaryFeed

SENTRY_ROOT = os.path.dirname(__file__) 

urlpatterns = patterns('',
    url(r'^_media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': os.path.join(SENTRY_ROOT, 'media')}, name='sentry-media'),

    # Feeds

    url(r'^feeds/%s/messages.xml$' % re.escape(KEY), MessageFeed(), name='sentry-feed-messages'),
    url(r'^feeds/%s/summaries.xml$' % re.escape(KEY), SummaryFeed(), name='sentry-feed-summaries'),

    # JS and API

    url(r'^jsapi/$', views.ajax_handler, name='sentry-ajax'),
    url(r'^store/$', views.store, name='sentry-store'),
    
    # Normal views

    url(r'^login$', views.login, name='sentry-login'),
    url(r'^logout$', views.logout, name='sentry-logout'),
    url(r'^group/(\d+)$', views.group, name='sentry-group'),
    url(r'^group/(\d+)/messages$', views.group_message_list, name='sentry-group-messages'),
    url(r'^group/(\d+)/messages/(\d+)$', views.group_message_details, name='sentry-group-message'),
    url(r'^group/(\d+)/actions/([\w_-]+)', views.group_plugin_action, name='sentry-group-plugin-action'),

    url(r'^$', views.index, name='sentry'),
)

server/urls.py
"""adds ebooks prefix to urls"""
from django.contrib import admin
from django.conf.urls.defaults import *

try:
    from settings import ROOT_URL
except ImportError:
    ROOT_URL = r''

from spec.logger import create_log

create_log()

admin.autodiscover()

urlpatterns = patterns('',
    (ROOT_URL, include('urls_root')),
)

server/django/contrib/messages/models.py
# Models module required so tests are discovered.

server/sentry/client/celery/models.py
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured

if 'djcelery' not in settings.INSTALLED_APPS:
    raise ImproperlyConfigured("Put 'djcelery' in your "
        "INSTALLED_APPS setting in order to use the sentry celery client.")

server/sentry/client/models.py
import sys
import logging
import warnings

from django.core.signals import got_request_exception
from django.db import  transaction

from sentry import conf

logger = logging.getLogger('sentry.errors')

_client = (None, None)
def get_client():
    global _client
    if _client[0] != conf.CLIENT:
        module, class_name = conf.CLIENT.rsplit('.', 1)
        _client = (conf.CLIENT, getattr(__import__(module, {}, {}, class_name), class_name)())
    return _client[1]
client = get_client()

@transaction.commit_on_success
def sentry_exception_handler(request=None, **kwargs):
    try:
        exc_type, exc_value, exc_traceback = sys.exc_info()

        if conf.DEBUG or getattr(exc_type, 'skip_sentry', False):
            return

        if transaction.is_dirty():
            transaction.rollback()

        extra = dict(
            request=request,
        )
        
        message_id = get_client().create_from_exception(**extra)
        if request:
            # attach the sentry object to the request
            request.sentry = {
                'id': message_id,
            }
    except Exception, exc:
        try:
            logger.exception(u'Unable to process log entry: %s' % (exc,))
        except Exception, exc:
            warnings.warn(u'Unable to process log entry: %s' % (exc,))

got_request_exception.connect(sentry_exception_handler)

server/sentry/models.py
import base64
try:
    import cPickle as pickle
except ImportError:
    import pickle
import datetime
import logging
import sys

from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.db import models, transaction
from django.db.models import Count
from django.db.models.signals import post_syncdb
from django.utils.encoding import smart_unicode
from django.utils.translation import ugettext_lazy as _

from sentry import conf
from sentry.helpers import cached_property, construct_checksum, get_db_engine, transform, get_filters
from sentry.manager import GroupedMessageManager, SentryManager
from sentry.reporter import FakeRequest

_reqs = ('paging', 'indexer')
for r in _reqs:
    if r not in settings.INSTALLED_APPS:
        raise ImproperlyConfigured("Put '%s' in your "
            "INSTALLED_APPS setting in order to use the sentry application." % r)

from indexer.models import Index

try:
    from idmapper.models import SharedMemoryModel as Model
except ImportError:
    Model = models.Model

__all__ = ('Message', 'GroupedMessage')

STATUS_LEVELS = (
    (0, _('unresolved')),
    (1, _('resolved')),
)

class GzippedDictField(models.TextField):
    """
    Slightly different from a JSONField in the sense that the default
    value is a dictionary.
    """
    __metaclass__ = models.SubfieldBase
 
    def to_python(self, value):
        if isinstance(value, basestring) and value:
            value = pickle.loads(base64.b64decode(value).decode('zlib'))
        elif not value:
            return {}
        return value

    def get_prep_value(self, value):
        if value is None: return
        return base64.b64encode(pickle.dumps(transform(value)).encode('zlib'))
 
    def value_to_string(self, obj):
        value = self._get_val_from_obj(obj)
        return self.get_db_prep_value(value)

    def south_field_triple(self):
        "Returns a suitable description of this field for South."
        from south.modelsinspector import introspector
        field_class = "django.db.models.fields.TextField"
        args, kwargs = introspector(self)
        return (field_class, args, kwargs)

class MessageBase(Model):
    logger          = models.CharField(max_length=64, blank=True, default='root', db_index=True)
    class_name      = models.CharField(_('type'), max_length=128, blank=True, null=True, db_index=True)
    level           = models.PositiveIntegerField(choices=conf.LOG_LEVELS, default=logging.ERROR, blank=True, db_index=True)
    message         = models.TextField()
    traceback       = models.TextField(blank=True, null=True)
    view            = models.CharField(max_length=200, blank=True, null=True)
    checksum        = models.CharField(max_length=32)
    data            = GzippedDictField(blank=True, null=True)

    objects         = SentryManager()

    class Meta:
        abstract = True

    def shortened_traceback(self):
        return '\n'.join(self.traceback.split('\n')[-5:])
    shortened_traceback.short_description = _('traceback')
    shortened_traceback.admin_order_field = 'traceback'
    
    def error(self):
        if self.message:
            message = smart_unicode(self.message)
            if len(message) > 100:
                message = message[:97] + '...'
            if self.class_name:
                return "%s: %s" % (self.class_name, message)
        else:
            message = self.class_name or ''
        return message
    error.short_description = _('error')

    def description(self):
        return self.traceback or ''
    description.short_description = _('description')

    def has_two_part_message(self):
        return '\n' in self.message.strip('\n')
    
    def message_top(self):
        return self.message.split('\n')[0]

class GroupedMessage(MessageBase):
    status          = models.PositiveIntegerField(default=0, choices=STATUS_LEVELS, db_index=True)
    times_seen      = models.PositiveIntegerField(default=1)
    last_seen       = models.DateTimeField(default=datetime.datetime.now, db_index=True)
    first_seen      = models.DateTimeField(default=datetime.datetime.now, db_index=True)

    objects         = GroupedMessageManager()

    class Meta:
        unique_together = (('logger', 'view', 'checksum'),)
        verbose_name_plural = _('grouped messages')
        verbose_name = _('grouped message')
        permissions = (
            ("can_view", "Can view"),
        )
        db_table = 'sentry_groupedmessage'

    def __unicode__(self):
        return "(%s) %s" % (self.times_seen, self.error())

    @models.permalink
    def get_absolute_url(self):
        return ('sentry-group', (self.pk,), {})

    def natural_key(self):
        return (self.logger, self.view, self.checksum)

    @classmethod
    def create_sort_index(cls, sender, db, created_models, **kwargs):
        # This is only supported in postgres
        engine = get_db_engine()
        if not engine.startswith('postgresql'):
            return
        if cls not in created_models:
            return

        from django.db import connections
        
        try:
            cursor = connections[db].cursor()
            cursor.execute("create index sentry_groupedmessage_score on sentry_groupedmessage ((%s))" % (cls.get_score_clause(),))
            cursor.close()
        except:
            transaction.rollback()
        
    @classmethod
    def get_score_clause(cls):
        engine = get_db_engine()
        if engine.startswith('postgresql'):
            return 'log(times_seen) * 600 + last_seen::abstime::int'
        if engine.startswith('mysql'):
            return 'log(times_seen) * 600 + unix_timestamp(last_seen)'
        return 'times_seen'

    def mail_admins(self, request=None, fail_silently=True):
        if not conf.ADMINS:
            return
        
        from django.core.mail import send_mail
        from django.template.loader import render_to_string

        message = self.message_set.order_by('-id')[0]

        obj_request = message.request

        subject = 'Error (%s IP): %s' % ((obj_request.META.get('REMOTE_ADDR') in settings.INTERNAL_IPS and 'internal' or 'EXTERNAL'), obj_request.path)
        if message.site:
            subject  = '[%s] %s' % (message.site, subject)
        try:
            request_repr = repr(obj_request)
        except:
            request_repr = "Request repr() unavailable"

        if request:
            link = request.build_absolute_url(self.get_absolute_url())
        else:
            link = '%s%s' % (conf.URL_PREFIX, self.get_absolute_url())

        body = render_to_string('sentry/emails/error.txt', {
            'request_repr': request_repr,
            'request': obj_request,
            'group': self,
            'traceback': message.traceback,
            'link': link,
        })
        
        send_mail(subject, body,
                  settings.SERVER_EMAIL, conf.ADMINS,
                  fail_silently=fail_silently)
    
    @property
    def unique_urls(self):
        return self.message_set.filter(url__isnull=False)\
                   .values_list('url', 'logger', 'view', 'checksum')\
                   .annotate(times_seen=Count('url'))\
                   .values('url', 'times_seen')\
                   .order_by('-times_seen')

    @property
    def unique_servers(self):
        return self.message_set.filter(server_name__isnull=False)\
                   .values_list('server_name', 'logger', 'view', 'checksum')\
                   .annotate(times_seen=Count('server_name'))\
                   .values('server_name', 'times_seen')\
                   .order_by('-times_seen')

    @property
    def unique_sites(self):
        return self.message_set.filter(site__isnull=False)\
                   .values_list('site', 'logger', 'view', 'checksum')\
                   .annotate(times_seen=Count('site'))\
                   .values('site', 'times_seen')\
                   .order_by('-times_seen')

    def get_version(self):
        if not self.data:
            return
        if 'version' not in self.data:
            return
        module = self.data.get('module', 'ver')
        return module, self.data['version']

class Message(MessageBase):
    message_id      = models.CharField(max_length=32, null=True, unique=True)
    group           = models.ForeignKey(GroupedMessage, blank=True, null=True, related_name="message_set")
    datetime        = models.DateTimeField(default=datetime.datetime.now, db_index=True)
    url             = models.URLField(verify_exists=False, null=True, blank=True)
    server_name     = models.CharField(max_length=128, db_index=True)
    site            = models.CharField(max_length=128, db_index=True, null=True)

    class Meta:
        verbose_name = _('message')
        verbose_name_plural = _('messages')
        db_table = 'sentry_message'

    def __unicode__(self):
        return self.error()

    def save(self, *args, **kwargs):
        if not self.checksum:
            self.checksum = construct_checksum(**self.__dict__)
        super(Message, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('sentry-group-message', (self.group_id, self.pk), {})
    
    def shortened_url(self):
        if not self.url:
            return _('no data')
        url = self.url
        if len(url) > 60:
            url = url[:60] + '...'
        return url
    shortened_url.short_description = _('url')
    shortened_url.admin_order_field = 'url'
    
    def full_url(self):
        return self.data.get('url') or self.url
    full_url.short_description = _('url')
    full_url.admin_order_field = 'url'

    @cached_property
    def request(self):
        fake_request = FakeRequest()
        fake_request.META = self.data.get('META') or {}
        fake_request.GET = self.data.get('GET') or {}
        fake_request.POST = self.data.get('POST') or {}
        fake_request.FILES = self.data.get('FILES') or {}

server/sentry/plugins/sentry_servers/models.py
from django.shortcuts import render_to_response
from django.template.loader import render_to_string

from sentry.plugins import GroupActionProvider

class ServerGroupPanel(GroupActionProvider):
    """Adds additional support for showing information about servers including:
    
    * A panel which shows all servers a message was seen on.
    * A sidebar module which shows the servers most actively seen on.
    """
    
    title = 'Servers'

    def panels(self, request, panel_list, group):
        panel_list.append((self.title, self.__class__.get_url(group.pk)))
        return panel_list

    def view(self, request, group):
        return render_to_response('sentry/plugins/sentry_servers/index.html', locals())
    
    def widget(self, request, group):
        return render_to_string('sentry/plugins/sentry_servers/widget.html', locals())

server/sentry/plugins/sentry_sites/models.py
from django.shortcuts import render_to_response
from django.template.loader import render_to_string

from sentry.plugins import GroupActionProvider

class SiteGroupPanel(GroupActionProvider):
    """Adds additional support for showing information about sites including:
    
    * A panel which shows all sites a message was seen on.
    * A sidebar module which shows the sites most actively seen on.
    """
    
    title = 'Sites'

    def panels(self, request, panel_list, group):
        panel_list.append((self.title, self.__class__.get_url(group.pk)))
        return panel_list

    def view(self, request, group):
        return render_to_response('sentry/plugins/sentry_sites/index.html', locals())
    
    def widget(self, request, group):
        return render_to_string('sentry/plugins/sentry_sites/widget.html', locals())

server/sentry/plugins/sentry_urls/models.py
from django.shortcuts import render_to_response
from django.template.loader import render_to_string

from sentry.plugins import GroupActionProvider

class ServerUrlsPanel(GroupActionProvider):
    """Adds additional support for showing information about urls including:
    
    * A panel which shows all urls a message was seen on.
    * A sidebar module which shows the urls most actively seen on.
    """
    
    title = 'URLs'

    def panels(self, request, panel_list, group):
        panel_list.append((self.title, self.__class__.get_url(group.pk)))
        return panel_list

    def view(self, request, group):
        return render_to_response('sentry/plugins/sentry_urls/index.html', locals())
    
    def widget(self, request, group):
        return render_to_string('sentry/plugins/sentry_urls/widget.html', locals())

server/sentry/templates/sentry/group/details.html
{% extends "sentry/index.html" %}

{% load sentry_helpers %}
{% load i18n %}

{% block title %}{{ group.error }} | Sentry{% endblock %}

{% block heading %}
    Message Details <span><a href="{% url sentry %}">&laquo; {% trans "Back to list" %}</a></span>
{% endblock %}

{% block content %}
    <div id="sidebar">
        <ul class="actions">
            {# We're going to move these to the resolve action location #}
            {% for label, link, is_active in group|get_actions:request %}
                <li><a href="{{ link }}">{{ label }}</a></li>
            {% endfor %}
        </ul>
        <h2>Meta</h2>
        <dl class="flat">
            <dt>Logger:</dt>
            <dd><a href="{% url sentry %}?logger={{ group.logger }}">{{ group.logger }}</a></dd>
            <dt>Level:</dt>
            <dd><a href="{% url sentry %}?level={{ group.level }}">{{ group.get_level_display }}</a></dd>
            <dt>Status:</dt>
            <dd>{{ group.get_status_display|title }}</dd>
            <dt>First Seen:</dt>
            <dd>{{ group.first_seen|timesince }}</dd>
            <dt>Last Seen:</dt>
            <dd>{{ group.last_seen|timesince }}</dd>
        </dl>
        
        {% for html in group|get_widgets:request %}
            {{ html|safe }}
        {% endfor %}
    </div>

    <div id="body" class="with-sidebar">
        <ul class="messages" id="message_list">
            <li class="{% cycle 'row1' 'row2' %} level-{{ group.level }} active" id="group_{{ group.pk }}" data-sentry-count="{{ group.times_seen }}">
                <span class="count count-digits-{{ group.times_seen|num_digits }}">{{ group.times_seen }}</span>
                <h3>{% if group.view %}{{ group.view }}{% else %}{{ group.message_top|truncatechars:100 }}{% endif %}</h3>
                <span class="last_seen">{{ group.last_seen|timesince }}</span>
                <span class="status status-{{ group.status }}">{{ group.get_status_display }}</span>
                <p class="message">
                    <span class="tag tag-level">{{ group.get_level_display }}</span> 
                    <span class="tag tag-logger">{{ group.logger }}</span> 
                    {% with group.get_version as version %}
                        {% if version %}
                            <span class="tag tag-version">{{ version.0 }} {{ version.1 }}</span> 
                        {% endif %}
                    {% endwith %}
                    {% for tag in group|get_tags:request %}<span class="tag">{{ tag }}</span> {% endfor %}
                    {{ group.error }}
                </p>
                {% if group.status == 0 %}
                    <a href="{% url sentry-ajax %}?op=resolve&amp;gid={{ group.pk }}" class="hidden button button_resolve">&#10003;</a>
                {% endif %}
            </li>
        </ul>

        <ul class="nav" id="group_nav">
            <li{% ifequal page 'details' %} class="active"{% endifequal %}><a href="{% url sentry-group group.pk %}">Details</a></li>
            <li{% ifequal page 'messages' %} class="active"{% endifequal %}><a href="{% url sentry-group-messages group.pk %}">Messages</a></li>
            {% for label, link, is_active in group|get_panels:request %}
                <li{% if is_active %} class="active"{% endif %}><a href="{{ link }}">{{ label }}</a></li>
            {% endfor %}
        </ul>
        
        {% block inner %}
            <div id="details">
                {% if group.has_two_part_message %}
                    <h2>Full Message</h2>
                    <pre id="full-message">{{ group.message }}</pre>
                {% endif %}
                
                {% if traceback %}
                    {{ traceback }}
                {% endif %}
                
                {% with group|chart_data as chart_data %}
                    {% if chart_data %}
                    <script type="text/javascript">
                    $(document).ready(function() {
                        new Highcharts.Chart({
                            chart: {
                                renderTo: 'chart',
                                zoomType: 'x',
                                marginLeft: 50,
                                marginRight: 20,
                                marginTop: 20,
                                marginBottom: 40,
                                backgroundColor: '#eeeeee',
                                showAxes: false,
                                height: 200
                            },
                            title: {
                                text: false
                            },
                            xAxis: {
                                type: 'datetime',
                                maxZoom: 24 * 3600000, // 1 day
                                title: {
                                    text: false
                                },
                                showFirstLabel: false,
                                dateTimeLabelFormats: {
                                    second: '%H:%M:%S',
                                    minute: '%H:%M',
                                    hour: '%d %b %H:%M',
                                    day: '%e. %b',
                                    week: '%e. %b',
                                    month: '%b \'%y',
                                    year: '%Y'
                                }
                            },
                            yAxis: {
                                title: {
                                    text: false
                                }
                            },
                            tooltip: {
                                formatter: function() {
                                    return '<strong>'+
                                        Highcharts.dateFormat('%A %B %e %Y<br/>%I:00 %p', this.x) + '</strong><br/>'+
                                        this.y+' records';
                                }
                            },
                            series: [{
                                pointStart: new Date() - {{ chart_data.points|length }} * 3600000,
                                pointInterval: 3600 * 1000,
                                type: 'area',
                                data: {{ chart_data.points|to_json }}
                            }],
                            legend: {
                                enabled: false
                            },
                            plotOptions: {
                                area: {
                                    lineWidth: 1,
                                    marker: {
                                        enabled: false,
                                        states: {
                                            hover: {
                                                enabled: true,
                                                radius: 5
                                            }
                                        }
                                    },
                                    shadow: false,
                                    states: {
                                        hover: {
                                            lineWidth: 1
                                        }
                                    }
                                }
                            },
                        });
                    });
                    </script>
                    <h2>Frequency</h2>
                    <div id="chart">
                        <noscript>Get yourself some JavaScripts dood</noscript>
                    </div>
                    {% endif %}
                {% endwith %}

                <div id="requestinfo">
                    <h2>{% trans "Additional Data" %}</h2>
                    <table>
                        {% for k, v in json_data %}
                            <tr>
                                <th class="key">{{ k }}</th>
                                <td class="values">
                                {% if v %}
                                    {% if v|is_dict %}
                                        <table class="vars">
                                            <thead>
                                                <tr>
                                                    <th>Variable</th>
                                                    <th>Value</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for k_, v_ in v.iteritems %}
                                                <tr>
                                                    <td>{{ k_ }}</td>
                                                    <td class="code"><pre>{{ v_|pprint }}</pre></td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    {% else %}
                                        {{ v|pprint }}
                                    {% endif %}
                                {% else %}
                                    <p>No data for {{ k }}</p>
                                {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
                
                {% if version_data %}
                    <div id="versioninfo">
                        <h2>Module Versions</h2>
                        <table>
                            {% for k, v in version_data %}
                                <tr>
                                    <th class="key">{{ k }}</th>
                                    <td class="values">{{ v }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                {% endif %}
            </div>
        {% endblock %}
    </div>
{% endblock %}

server/sentry/templates/sentry/group/message.html
{% extends "sentry/group/details.html" %}

{% load paging_extras %}
{% load sentry_helpers %}

{% block title %}{{ group.error }} | Sentry{% endblock %}

{% block inner %}
    <ul class="messages" id="message_list">
        <li class="row1 active level-{{ message.level }}" data-sentry-count="{{ message.times_seen }}">
            <h3>
                {{ message.message_top|truncatechars:100 }}
                {% if message.url %}
                     on {{ message.url }}
                {% endif %}
            </h3>
            <span class="status status-{{ message.status }}">{{ message.get_status_display }}</span>
            <p class="message">
                {% if message.message_id %}
                    <span class="tag tag-id">{{ message.message_id }}</span>
                {% endif %}
                <span class="tag tag-level">{{ message.get_level_display }}</span>
                <span class="tag tag-server">{{ message.server_name }}</span>
                {% with message.get_version as version %}
                    {% if version %}
                        <span class="tag tag-version">{{ version.0 }} {{ version.1 }}</span> 
                    {% endif %}
                {% endwith %}
                <span class="last_seen">{{ message.datetime|timesince }}</span>
            </p>
        </li>
        
    </ul>

    {% if traceback %}

        <h2>Traceback</h2>

        {{ traceback }}

    {% endif %}

    <div id="requestinfo">
        <h2>More Information</h2>

        <table>
            {% for k, v in json_data %}
                <tr>
                    <th class="key">{{ k }}</th>
                    <td class="values">
                    {% if v %}
                        {% if v|is_dict %}
                            <table class="vars">
                                <thead>
                                    <tr>
                                        <th>Variable</th>
                                        <th>Value</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for k_, v_ in v.iteritems %}
                                    <tr>
                                        <td>{{ k_ }}</td>
                                        <td class="code"><pre>{{ v_|pprint }}</pre></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            {{ v|pprint }}
                        {% endif %}
                    {% else %}
                        <p>No data for {{ k }}</p>
                    {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

server/sentry/templates/sentry/group/message_list.html
{% extends "sentry/group/details.html" %}

{% load paging_extras %}

{% block inner %}
    <h2>Message List</h2>
    {% paginate message_list from request as message_list per_page 15 %}
    <div class="clearfix">
        {{ message_list.paging }}
    </div>
    <ul class="messages" id="message_list">
        {% for message in message_list.objects %}
            {% include "sentry/partial/_message.html" %}
        {% endfor %}
    </ul>
    <div class="clearfix">
        {{ message_list.paging }}
    </div>
{% endblock %}